### ISSUE TITLE
Panic when can't open ~/.docker/config.json

### ISSUE THREAD

**Issue by lewismarshall** [appvia/artefactor#24]
When publishing, if the docker config doesn't exists, a panic occurs:

```
[vincentlam@td-dsp01 crown-high-elk]$ ../artefactor_linux_amd64 publish --docker-registry registry.dsp.internal
Loading image from downloads/quay.io~ukhomeofficedigital~elasticsearch~~v1.5.1.docker.tar.
ReTagging image as registry.dsp.internal/elasticsearch:v1.5.1.
pushing image registry.dsp.internal/elasticsearch:v1.5.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75a5f2]

goroutine 1 [running]:
github.com/appvia/artefactor/pkg/docker.GetAuth(0xc42036e570, 0x2a, 0x0, 0x0)
    /Users/vincent/go/src/github.com/appvia/artefactor/pkg/docker/config.go:17 +0x92
github.com/appvia/artefactor/pkg/docker.Push(0xc42036e570, 0x2a, 0xc42024fb48, 0x1)
    /Users/vincent/go/src/github.com/appvia/artefactor/pkg/docker/push.go:33 +0x83
github.com/appvia/artefactor/pkg/cmd.publish(0xda84c0, 0x0, 0x0)
    /Users/vincent/go/src/github.com/appvia/artefactor/pkg/cmd/publish.go:76 +0x5e8
github.com/appvia/artefactor/pkg/cmd.glob..func2(0xda84c0, 0xc420374300, 0x0, 0x2, 0x0, 0x0)
    /Users/vincent/go/src/github.com/appvia/artefactor/pkg/cmd/publish.go:23 +0x2b
github.com/appvia/artefactor/vendor/github.com/spf13/cobra.(*Command).execute(0xda84c0, 0xc420374260, 0x2, 0x2, 0xda84c0, 0xc420374260)
    /Users/vincent/go/src/github.com/appvia/artefactor/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/appvia/artefactor/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xda8260, 0xda8260, 0xc42024ff78, 0x403dfc)
    /Users/vincent/go/src/github.com/appvia/artefactor/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/appvia/artefactor/vendor/github.com/spf13/cobra.(*Command).Execute(0xda8260, 0x1, 0x0)
    /Users/vincent/go/src/github.com/appvia/artefactor/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/appvia/artefactor/pkg/cmd.Execute()
    /Users/vincent/go/src/github.com/appvia/artefactor/pkg/cmd/artefactor.go:101 +0x2d
main.main()
    /Users/vincent/go/src/github.com/appvia/artefactor/cmd/artefactor/artefactor.go:21 +0x20
```

**Comment by lewismarshall** [comment]
Fixed by #27
