### ISSUE TITLE
Panic when images don't exist within restored repo

### ISSUE THREAD

**Issue by vinn946** [appvia/artefactor#42]
```
[vincentlam@td-dsp01 kube-gitlab]$ DEPLOY_TO=dc1_test ./scripts/deploy.sh
[INFO] deploying to: dc1_test
[INFO] kube api url: https://10.xx.xx.126:6443
[INFO] namespace: gitlab
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72221b]

goroutine 1 [running]:
github.com/appvia/artefactor/pkg/hashcache.GetFiles(0xa3e838, 0x9, 0x4763e1, 0xffffffffffffff9c, 0xc42025d9d8)
	/go/src/github.com/appvia/artefactor/pkg/hashcache/sha256.go:232 +0xbb
github.com/appvia/artefactor/pkg/docker.GetImages(0xa3e838, 0x9, 0xc42002016b, 0x15, 0x0, 0x0, 0xa3e8bf, 0xa3ed7e, 0x9)
	/go/src/github.com/appvia/artefactor/pkg/docker/docker.go:68 +0x6a
github.com/appvia/artefactor/pkg/cmd.imageNames(0xdb8320, 0x0, 0x0)
	/go/src/github.com/appvia/artefactor/pkg/cmd/image-names.go:58 +0x228
github.com/appvia/artefactor/pkg/cmd.glob..func2(0xdb8320, 0xddc8f0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/appvia/artefactor/pkg/cmd/image-names.go:24 +0x2b
github.com/appvia/artefactor/vendor/github.com/spf13/cobra.(*Command).execute(0xdb8320, 0xddc8f0, 0x0, 0x0, 0xdb8320, 0xddc8f0)
	/go/src/github.com/appvia/artefactor/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/appvia/artefactor/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xdb80c0, 0xdb8210, 0xc42025df78, 0x405c3c)
	/go/src/github.com/appvia/artefactor/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/appvia/artefactor/vendor/github.com/spf13/cobra.(*Command).Execute(0xdb80c0, 0x1, 0x0)
	/go/src/github.com/appvia/artefactor/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/appvia/artefactor/pkg/cmd.Execute()
	/go/src/github.com/appvia/artefactor/pkg/cmd/artefactor.go:109 +0x2d
main.main()
	/go/src/github.com/appvia/artefactor/cmd/artefactor/artefactor.go:21 +0x20
```

**Comment by lewismarshall** [comment]
Fixed by #43
